version: "3.9"
services:
  valou-web:
    build: .
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
    command: [yarn, dev]
    ports:
      - "3000:3000"
